### ISSUE TITLE
Idea: Have an arguments property that gets sent to the action

### ISSUE THREAD

**Issue by markrickert** [codelation/menu-motion#15]
so someone could define:

``` ruby
{
  title: "Some Action",
  target: self,
  action: :some_action,
  arguments: {
    some: 'arguments',
    or_whatever: BigDecimal.new('15.43')
  }
}
```

and that would call:

``` ruby
def some_action(arguments = {})
  # arguments passed PLUS sender
end

# or if this is defined:
def some_action
  # Just call the action and output a warning that they passed arguments 
  # that aren't being used by the called method.
end
```

The only issue would be that we might have to do an if/else chain to determine if they've implemented simply `some_action` (and output a warning) or `some_action(arguments)` (with `x.respond_td?`). That way, we can always send the `sender` to the method without having to use a string with the ":" at the end to indicate the difference of an action with a `sender` parameter or an action without one.

Thoughts?

**Comment by brianpattison** [comment]
@markrickert You can currently do this: 

``` ruby
{
  title: "Hello",
  target: self,
  action: "hello:",
  object: {
    some: 'arguments',
    or_whatever: BigDecimal.new('15.43')
  }
}

def hello(sender)
  puts sender.object # Alias for sender.representedObject
end
```

I guess I don't know if that's good enough for what you're trying to do...?

**Comment by markrickert** [comment]
Ahh cool. I'm not necessarily trying to _do_ anything, but had an idea for a feature that people might want to use. Sending the arguments through the `sender.object` doesn't seem like the very "Ruby" way to do things, which is why I didn't even think it was possible with the current codebase.

could maybe use some more documentation of that feature :)

**Comment by brianpattison** [comment]
@markrickert More documentation is necessary, and I should probably add `represented_object` as a key that can be used along with `object` to have it match up with the iOS API and what someone might try to do if they already know about `NSMenuItem#representedObject`.
